import { SUPABASE_URL, SUPABASE_ANON_KEY, supabaseConfigured } from './config.js';
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const supabase=supabaseConfigured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null; const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)]; const fmt=n=>`PKR ${Number(n||0).toLocaleString('en-PK')}`;
let allProducts=[],allOrders=[];
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
if(!supabaseConfigured)$('#configWarning').classList.remove('hidden');

async function isAdmin(user){if(!user||!supabase)return false;const {data,error}=await supabase.rpc('is_admin');return !error&&data===true}
async function showSession(){if(!supabase)return;const {data:{session}}=await supabase.auth.getSession();if(session&&await isAdmin(session.user)){showAdmin(session.user);await loadAll()}else if(session){await supabase.auth.signOut();toast('This account is not authorized as admin')}}
function showAdmin(user){$('#loginWrap').classList.add('hidden');$('#adminShell').classList.remove('hidden');$('#adminEmail').textContent=user.email}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!supabase)return toast('Configure Supabase first');const fd=new FormData(e.target);const {data,error}=await supabase.auth.signInWithPassword({email:fd.get('email'),password:fd.get('password')});if(error)return toast(error.message);if(!await isAdmin(data.user)){await supabase.auth.signOut();return toast('Not authorized as admin')}showAdmin(data.user);await loadAll()};
$('#signupBtn').onclick=async()=>{if(!supabase)return toast('Configure Supabase first');const form=$('#loginForm');const fd=new FormData(form);const email=fd.get('email'),password=fd.get('password');if(!email||!password)return toast('Enter email and password first');const {error}=await supabase.auth.signUp({email,password});if(error)return toast(error.message);toast('Account created. Confirm email if required, then sign in.')};
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();location.reload()};
$$('.nav-btn[data-section]').forEach(b=>b.onclick=()=>{const s=b.dataset.section;$$('.nav-btn[data-section]').forEach(x=>x.classList.toggle('active',x===b));$$('.content-section').forEach(x=>x.classList.toggle('active',x.id===s));$('#pageTitle').textContent=b.textContent.trim()});
async function loadAll(){await Promise.all([loadProducts(),loadOrders(),loadContent(),loadNewsletter()]);renderStats()}
async function loadProducts(){const {data,error}=await supabase.from('products').select('*').order('sort_order');if(error)return toast(error.message);allProducts=data||[];$('#productsTable').innerHTML=allProducts.map(p=>`<tr><td><img class="thumb" src="${p.image_url||'assets/images/product1.jpg'}"></td><td>${p.name}<div class="muted">${p.sku||''}</div></td><td>${fmt(p.price)}</td><td>${p.stock}</td><td>${p.is_active?'Yes':'No'}</td><td><div class="row-actions"><button class="ghost-btn" data-edit-product="${p.id}">EDIT</button></div></td></tr>`).join('')}
async function loadOrders(){const {data,error}=await supabase.from('orders').select('*').order('created_at',{ascending:false});if(error)return toast(error.message);allOrders=data||[];$('#ordersTable').innerHTML=allOrders.map(o=>`<tr><td>${o.order_number}</td><td>${o.customer_name}</td><td>${o.phone}</td><td>${o.city}</td><td>${fmt(o.total)}</td><td><select data-order-status="${o.id}"><option ${o.status==='new'?'selected':''}>new</option><option ${o.status==='confirmed'?'selected':''}>confirmed</option><option ${o.status==='shipped'?'selected':''}>shipped</option><option ${o.status==='completed'?'selected':''}>completed</option><option ${o.status==='cancelled'?'selected':''}>cancelled</option></select></td><td>${new Date(o.created_at).toLocaleString()}</td></tr>`).join('');$('#recentOrders').innerHTML=allOrders.slice(0,7).map(o=>`<tr><td>${o.order_number}</td><td>${o.customer_name}</td><td>${fmt(o.total)}</td><td><span class="pill ${o.status}">${o.status}</span></td><td>${new Date(o.created_at).toLocaleDateString()}</td></tr>`).join('')}
function renderStats(){$('#statProducts').textContent=allProducts.filter(p=>p.is_active).length;$('#statOrders').textContent=allOrders.length;$('#statRevenue').textContent=fmt(allOrders.filter(o=>o.status!=='cancelled').reduce((a,b)=>a+Number(b.total),0));$('#statLowStock').textContent=allProducts.filter(p=>p.stock<=5).length}
async function loadContent(){const {data}=await supabase.from('site_settings').select('*').eq('id','main').maybeSingle();if(!data)return;Object.entries(data).forEach(([k,v])=>{const el=$(`#contentForm [name="${k}"]`);if(el)el.value=v??''})}
async function loadNewsletter(){const {data,error}=await supabase.from('newsletter').select('*').order('created_at',{ascending:false});if(error)return;$('#newsletterTable').innerHTML=(data||[]).map(x=>`<tr><td>${x.email}</td><td>${new Date(x.created_at).toLocaleString()}</td></tr>`).join('')}
$('#refreshOrders').onclick=async()=>{await loadOrders();renderStats();toast('Orders refreshed')};
document.addEventListener('change',async e=>{const el=e.target.closest('[data-order-status]');if(!el)return;const {error}=await supabase.from('orders').update({status:el.value}).eq('id',el.dataset.orderStatus);if(error)return toast(error.message);toast('Order status updated');await loadOrders();renderStats()});
function openProduct(p=null){const f=$('#productForm');f.reset();f.id.value=p?.id||'';f.name.value=p?.name||'';f.price.value=p?.price||'';f.stock.value=p?.stock??0;f.sort_order.value=p?.sort_order??0;f.sku.value=p?.sku||'';f.collection.value=p?.collection||'DROP 001';f.image_url.value=p?.image_url||'';f.is_active.value=String(p?.is_active??true);$('#deleteProductBtn').classList.toggle('hidden',!p);$('#productModalTitle').textContent=p?'Edit Product':'Add Product';$('#productModal').classList.add('open')}
$('#addProductBtn').onclick=()=>openProduct();$('#closeProductModal').onclick=()=>$('#productModal').classList.remove('open');
document.addEventListener('click',e=>{const b=e.target.closest('[data-edit-product]');if(b)openProduct(allProducts.find(p=>String(p.id)===b.dataset.editProduct))});
async function uploadImage(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`products/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from('product-images').upload(path,file,{upsert:false});if(error)throw error;return supabase.storage.from('product-images').getPublicUrl(path).data.publicUrl}
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=e.target;const fd=new FormData(f);let image_url=fd.get('image_url')||'';const file=$('#imageFile').files[0];try{if(file)image_url=await uploadImage(file)}catch(err){return toast(err.message)}const payload={name:fd.get('name'),price:Number(fd.get('price')),stock:Number(fd.get('stock')||0),sort_order:Number(fd.get('sort_order')||0),sku:fd.get('sku')||null,collection:fd.get('collection')||null,image_url,is_active:fd.get('is_active')==='true'};const id=fd.get('id');const q=id?supabase.from('products').update(payload).eq('id',id):supabase.from('products').insert(payload);const {error}=await q;if(error)return toast(error.message);$('#productModal').classList.remove('open');toast('Product saved');await loadProducts();renderStats()};
$('#deleteProductBtn').onclick=async()=>{const id=$('#productForm').id.value;if(!id||!confirm('Delete this product?'))return;const {error}=await supabase.from('products').delete().eq('id',id);if(error)return toast(error.message);$('#productModal').classList.remove('open');toast('Product deleted');await loadProducts();renderStats()};
$('#contentForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const payload={id:'main'};for(const [k,v] of fd.entries())payload[k]=v;const {error}=await supabase.from('site_settings').upsert(payload);if(error)return toast(error.message);toast('Homepage content saved')};
showSession();
